# Generated by Django 2.0.5 on 2018-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='floor',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='rooms',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='surface',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='localization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
