# Generated by Django 2.0.5 on 2018-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_auto_20180902_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
