# Generated by Django 2.0.5 on 2018-09-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0003_auto_20180906_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='longitude',
        ),
    ]
